### ISSUE TITLE
Is http://camdenre.github.io/src/app/html/EquationEditor re-rendering at every step?

### ISSUE THREAD

**Issue by haskellwukong** [camdenre/equation-editor#6]
Hi,

  In http://camdenre.github.io/src/app/html/EquationEditor , when a change is made to the "ENTER YOUR EQUATION HERE" does it re-render the entire expression (via MathJax), or have you somehow converted MathJax from a BATCH to an INteractive system?

Thanks!

**Comment by camdenre** [comment]
Hello haskellwukong,

I am actually not using MathJax at all. I have written my own formatting engine. I am only using the MathJax fonts.
